### PR TITLE
New Style Office_2010_Extended

### PR DESCRIPTION
**Pull request by Baldemaier**

### CODE REVIEW

**Comment by adriancs2** [comment]
Merged, thanks!

**Comment by catterpiler74** [comment]
Can u build project and add to release tab (need net 2.0 .dll), thanks.

**Comment by adriancs2** [comment]
@catterpiler74 , done, new release published, included .net 2.0 dll. you're welcome.
https://github.com/RibbonWinForms/RibbonWinForms/releases

**Comment by catterpiler74** [comment]
@adriancs2 , thank you.

**Pull request merged**
